package secao_u.com.netbiis.lojavirtual.JPA;
// Generated 7 de nov. de 2022 21:22:12 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente")
public class Cliente implements java.io.Serializable {

	private String cpf;
	private String nome;
	private String email;
	private Set<Pagamento> pagamentos = new HashSet<Pagamento>(0);

	public Cliente() {
	}

	public Cliente(String cpf, String nome, String email) {
		this.cpf = cpf;
		this.nome = nome;
		this.email = email;
	}
	
	@Override
	public String toString() {
		return "Cliente [ cpf="+cpf+" nome= "+nome +" email= "+email+" ]";
	}

	public Cliente(String cpf, String nome, String email, Set<Pagamento> pagamentos) {
		this.cpf = cpf;
		this.nome = nome;
		this.email = email;
		this.pagamentos = pagamentos;
	}

	@Id

	@Column(name = "cpf", unique = true, nullable = false, length = 12)
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@Column(name = "nome", nullable = false, length = 60)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "email", nullable = false, length = 60)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Pagamento> getPagamentos() {
		return this.pagamentos;
	}

	public void setPagamentos(Set<Pagamento> pagamentos) {
		this.pagamentos = pagamentos;
	}

}
