package secao_u.com.netbiis.lojavirtual.JPA;
// Generated 7 de nov. de 2022 21:22:12 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name = "curso")
public class Curso implements java.io.Serializable {

	private Integer cdCurso;
	private String nome;
	private BigDecimal valor;
	private String url;
	private Set<Pagamento> pagamentos = new HashSet<Pagamento>(0);

	public Curso() {
	}

	public Curso(String nome, BigDecimal valor, String url) {
		this.nome = nome;
		this.valor = valor;
		this.url = url;
	}

	public Curso(String nome, BigDecimal valor, String url, Set<Pagamento> pagamentos) {
		this.nome = nome;
		this.valor = valor;
		this.url = url;
		this.pagamentos = pagamentos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cdCurso", unique = true, nullable = false)
	public Integer getCdCurso() {
		return this.cdCurso;
	}

	public void setCdCurso(Integer cdCurso) {
		this.cdCurso = cdCurso;
	}

	@Column(name = "nome", nullable = false, length = 60)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "valor", nullable = false, precision = 6)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@Column(name = "url", nullable = false, length = 60)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "curso")
	public Set<Pagamento> getPagamentos() {
		return this.pagamentos;
	}

	public void setPagamentos(Set<Pagamento> pagamentos) {
		this.pagamentos = pagamentos;
	}

}
