package secao_u.com.netbiis.lojavirtual.JPA;
// Generated 7 de nov. de 2022 21:22:12 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Pagamento generated by hbm2java
 */
@Entity
@Table(name = "pagamento", uniqueConstraints = @UniqueConstraint(columnNames = "idpagamento"))
public class Pagamento implements java.io.Serializable {

	private PagamentoId id;
	private Cliente cliente;
	private Curso curso;
	private int idpagamento;
	private String datainscricao;

	public Pagamento() {
	}

	public Pagamento(PagamentoId id, Cliente cliente, Curso curso, int idpagamento, String datainscricao) {
		this.id = id;
		this.cliente = cliente;
		this.curso = curso;
		this.idpagamento = idpagamento;
		this.datainscricao = datainscricao;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cpf", column = @Column(name = "cpf", nullable = false, length = 12)),
			@AttributeOverride(name = "cdCurso", column = @Column(name = "cdCurso", nullable = false)) })
	public PagamentoId getId() {
		return this.id;
	}

	public void setId(PagamentoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cpf", nullable = false, insertable = false, updatable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cdCurso", nullable = false, insertable = false, updatable = false)
	public Curso getCurso() {
		return this.curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

	@Column(name = "idpagamento", unique = true, nullable = false)
	public int getIdpagamento() {
		return this.idpagamento;
	}

	public void setIdpagamento(int idpagamento) {
		this.idpagamento = idpagamento;
	}

	@Column(name = "datainscricao", nullable = false, length = 10)
	public String getDatainscricao() {
		return this.datainscricao;
	}

	public void setDatainscricao(String datainscricao) {
		this.datainscricao = datainscricao;
	}

}
