package secao_u.com.netbiis.lojavirtual.hibernate;
// Generated 12 de nov. de 2022 19:24:24 by Hibernate Tools 4.3.6.Final

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private int cpf;
	private String nome;
	private String email;

	public Cliente() {
	}

	public Cliente(int cpf, String nome, String email) {
		this.cpf = cpf;
		this.nome = nome;
		this.email = email;
	}

	public int getCpf() {
		return this.cpf;
	}

	public void setCpf(int cpf) {
		this.cpf = cpf;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
